POST http://{{serverUrl}}/api/register-user
Content-Type: application/x-www-form-urlencoded
Accept: application/json

email={{email}}&username={{username}}&password={{password}}&salutation=male

###

GET http://{{serverUrl}}/api/activate-user?c=cfef40103e2669b409817386d376b863defdcf1c
Accept: application/json
