POST http://{{serverUrl}}/api/register-user
Content-Type: application/x-www-form-urlencoded
Accept: application/json

email={{email}}&username={{username}}&password={{password}}&salutation=male

###

GET http://{{serverUrl}}/api/activate-user?c=de89566190bd9d984b3faecfa4a42d73c5528014
Accept: application/json


